// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $_islands_TabViewBody from "./routes/(_islands)/TabViewBody.tsx";
import * as $_islands_TabViewHeader from "./routes/(_islands)/TabViewHeader.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./routes/(_islands)/TabViewBody.tsx": $_islands_TabViewBody,
    "./routes/(_islands)/TabViewHeader.tsx": $_islands_TabViewHeader,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
